### ISSUE TITLE
How to set onlyEmojiClassName prop when using toArray?

### ISSUE THREAD

**Issue by ibc** [tommoor/react-emoji-render#12]
`toArray()` returns an array of text and emoji components. So, how to set the desired custom `onlyEmojiClassName` prop into those emoji components?

**Comment by ibc** [comment]
Or in other words, how do I take the `Emoji` element generated by `toArray()` and provide it with a `key` prop (in case I need it)?

**Comment by tommoor** [comment]
Cleaning up old issues, please reopen if you still care for this functionality
