### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by mccambridge** [tommoor/react-emoji-render#17]
The Twemoji component breaks my app in IE. You're trying to use `String.endsWith`, which is not supported at all in IE. You should be able to use `String.match` to achieve the same purpose and not break IE.

**Comment by enzoferey** [comment]
After IE discontinuation, and looking at the quite good support on [caniuse](https://caniuse.com/?search=endsWith), I'm closing this issue as I consider it non relevant anymore. If this is an issue for you, please comment down below and we will figure a way out.
