### ISSUE TITLE
Since 0.4.5, URLs are also converted into emojis

### ISSUE THREAD

**Issue by ibc** [tommoor/react-emoji-render#20]
This happens definitely since 0.4.5 (this [PR](https://github.com/tommoor/react-emoji-render/pull/19)).

```js
import Emoji, { toArray } from 'react-emoji-render';

// Within the component render():

const text = "https://google.foo :)";
const values = [];
const items = toArray(text);
let idx = 0;

for (const item of items)
{
  values.push(
    <Emoji
      key={idx++}
      text={item.props.children}
      options={{ className: 'emoji' }}
    />
  );
}

return (
  <div>{values}</div>
);
```

This code is generating this:

`https😕/google.foo 😃`

As you can see, the `:/` chars within the URL are also being converted into an emoji. Something tells me that it shouldn't go so far.

I'm not sure what the solution should be, but IMHO it would make sense if the parser requires some space, tab, dot, comma or similar char before or after the matched emoji symbol.

**Comment by tommoor** [comment]
I guess we need to get some URL's in the test suite

**Comment by ibc** [comment]
So, just to confirm, no emoji should be detected within something that looks like an URL, right?

**Comment by VictorVolovik** [comment]
Can confirm the same!

**Comment by tommoor** [comment]
Correct - the correct fix is to adjust the regex to stop this alias from triggering when part of a URL. This will mean undoing some of the changes in #19 and adding a regression spec.

If this is a problem for anyone in the meantime you can lock the dependency to < 0.4.5

**Comment by brookback** [comment]
Can't we force whitespace between `:shortnames:`, in order to not mess up `http://` strings?

Like:

```
shortnameRegexp = /\B:([\w+-]+):/g
```

**Comment by tommoor** [comment]
Yes. CC @enzoferey I believe some of your work will need to be undone here. 

https://github.com/tommoor/react-emoji-render/pull/19/files#diff-be46e2cd4b4d907bca18a445775a9f6aR136

**Comment by enzoferey** [comment]
Hi ! Yes, I believe URLs should be an edge case and we need tests for them. I can look at a solution tomorrow if that's okay for you.

**Comment by tommoor** [comment]
Sure, if you'd like to try making them an exception go for it!

If the library ends up having to support one or the other then not breaking url's is far more important than emoji's without a space between 😉

**Comment by brookback** [comment]
I applied

```
(^|\s)
```

to the beginning of the ASCII regex, in order to force it to be either in the beginning of a text line or have whitespace before it. Works great ✨

**Comment by enzoferey** [comment]
Please look at the referenced PR (https://github.com/tommoor/react-emoji-render/pull/23) 👍

**Comment by ibc** [comment]
Thanks guys, I confirm that it works great now in all the cases I've tested.

**Comment by enzoferey** [comment]
Let us know if you find any other edge case, they should be easy to add thanks to the way I refactored the regex :+1:

**Comment by ibc** [comment]
Sure, I'll do.
