### ISSUE TITLE
Update EmojiOne to 4.0

### ISSUE THREAD

**Issue by wilg** [tommoor/react-emoji-render#25]
This project uses EmojiOne 2.x, but there is a 4.0 version with more up-to-date icons. It's on a different CDN though: https://cdn.jsdelivr.net/emojione/assets/4.0/png/128/1f600.png

**Comment by enzoferey** [comment]
As I answered you in the other issue, to render that emoji we would need to update the EmojiOne cdn version (if the emoji didn't exist in 2.x) and then add it to the list of aliases.

**Comment by tommoor** [comment]
Very happy to accept a PR – I don't think it would be too involved but I'm not currently using this library in any production libraries so not top of list for me.
