### ISSUE TITLE
Does not properly render "👩‍⚕️"

### ISSUE THREAD

**Issue by wilg** [tommoor/react-emoji-render#26]
I am unable to get the character 👩‍⚕️to render properly.

https://www.emojione.com/emoji/1f469-2695

It's available in Emojione 4.0 (https://github.com/tommoor/react-emoji-render/issues/25) at https://cdn.jsdelivr.net/emojione/assets/4.0/png/128/1f469-2695.png

**Comment by enzoferey** [comment]
That's because the emoji is not in the list of aliases, so the library doesn't transform it:

https://github.com/tommoor/react-emoji-render/blob/master/data/aliases.js

**Comment by wilg** [comment]
Aren't the aliases for doing the `:+1:` GitHub/Slack style emojis? The case I am talking about is just typing this character from the macOS/iOS emoji picker, so it should just be the unicode character directly.

**Comment by wilg** [comment]
This project creates a url of `1f469-200d-2695-fe0f` rather than the `1f469-2695` that emojione seems to expect. I'm not an emoji expert, so I'm not sure why that would be.

Here's a modification of the demo to show this: http://requirebin.com/?gist=fc94a8e4e0cec4b27f74674bd53d8e9a

**Comment by wilg** [comment]
I think it has to do with the EmojiOne URL scheme, as I mentioned in the OP EmojiOne has it at

https://cdn.jsdelivr.net/emojione/assets/4.0/png/128/1f469-2695.png

but the URL this library generates is this one, which does not work:

https://cdn.jsdelivr.net/emojione/assets/4.0/png/128/1f469-200d-2695-fe0f.png

**Comment by enzoferey** [comment]
I'm working on upgrading to EmojiOne 4.0, we will see later if this issue remains.
