### ISSUE TITLE
Text property doesn't render dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by saadaouad** [tommoor/react-emoji-render#29]
In first I'd like to thank you for this great tool, I just noticed that text property doesn't render `dangerouslySetInnerHTML`, could be please provide us with an example if this was already implemented.

**Comment by saadaouad** [comment]
Hi @enzoferey , `toArray()` function it will gives an array and emoji will be an object, what I want to know is how we can display this object or property (inside this object) as an emoji?

And if we are using to `toArray()` we should avoid using `dangerouslySetInnerHTML` as it's mentioned on the readme https://github.com/tommoor/react-emoji-render#array-output

**Comment by enzoferey** [comment]
Hello again !

So I have no idea why @tommoor wrote that in the documentation, I'm not aware of any issues about putting unicode inside `dangerouslySetInnerHTML` and the remaining string is just html, there shouldn't be any problems. But we can sort around it if you like 😉 

I have setup a CodeSandbox example where I show one way of solving your problem directly put the emojis inside `dangerouslySetInnerHTML` and one way of solving it without putting the emojis inside `dangerouslySetInnerHTML`. As expected, both work, so I wonder the reason of that warning in the README 😅 

[CodeSandbox example](https://codesandbox.io/s/xjpy58llxq)

I hope that helps !

**Comment by saadaouad** [comment]
Great @enzoferey it's clear now, thank you so much 👍 

In my opinion the second function would be great:

```javascript
import React from 'react';
import {toArray} from 'react-emoji-render';

function parseEmojisAndHtml(value) {
  const innerHTMLArray = toArray(value);
  const innerHTMLOutput = innerHTMLArray.map((element, index) => {
    if (typeof element === 'string') {
      return <span key={index} dangerouslySetInnerHTML={{__html: element}} />;
    }
    return element.props.children;
  });
  return innerHTMLOutput;
}

export default parseEmojisAndHtml;
```

What do you think to integrate it on this package?

**Comment by tommoor** [comment]
The warning is just a general warning arounding using that prop. The toArray helper is provided so there should be no reason to dangerouslySetInnerHTML ☺️

**Comment by enzoferey** [comment]
> The warning is just a general warning arounding using that prop. The toArray helper is provided so there should be no reason to dangerouslySetInnerHTML ☺️

@tommoor Mmm 🤔 How not having the `toArray` helper would make you need `dangerouslySetInnerHTML` more ? I don't see any case 😅 

> What do you think to integrate it on this package?

@saadaouad I would say it doesn't make that much sense ? I think that is kinda of stepping in the user's business logic. The `toArray` helper already provides a way of parsing the emojis so pure JS function like this one could be written by the user depending on his use case. What I would say is a good idea is to add it to the README section of `toArray` as an example of further processing.

What do you guys think ?

**Comment by saadaouad** [comment]
> The `toArray` helper already provides a way of parsing the emojis so pure JS function like this one could be written by the user depending on his use case.

What I thought about it is to keep `toArray` helper and offer a new `react-emoji-render` helper's that can parse emojis and html in the same time.

> What I would say is a good idea is to add it to the README section of `toArray` as an example of further processing.
What do you guys think ?

Or let's boost the README with an example

**Comment by enzoferey** [comment]
> What I thought about it is to keep `toArray` helper and offer a new `react-emoji-render` helper's that can parse emojis and html in the same time.

Yes, I know. But in this case I think it steps in too much into user's use case as I said. For example, to parse emojis and HTML we are using `dangerouslySetInnerHTML` + a `<span/>` container, but I think that should be a choice of the user. He might want to do something else. I don't see it as something that `react-emoji-render` should take care off.

**Comment by saadaouad** [comment]
Good point @enzoferey 😄  , so let's just boost the README with an example.

**Comment by enzoferey** [comment]
Done ! https://github.com/tommoor/react-emoji-render/pull/30 Thanks for pointing this unclear part @saadaouad 👍

**Comment by saadaouad** [comment]
Thanks for your help too @enzoferey +1

**Comment by tommoor** [comment]
> How not having the `toArray` helper would make you need `dangerouslySetInnerHTML` more ? I don't see any case

The reason is that you can render an array of strings and React components directly in React. eg:

```javascript
<p>{toArray(myStringWithEmojis)}</p>
```

**Comment by enzoferey** [comment]
> The reason is that you can render an array of strings and React components directly in React

Right, having `toArray` makes it straightforward to render an output without using the library's components. In your example, if the string has some HTML you will still need to parse it somehow. Having used `toArray` before the HTML parsing doesn't change anything about the fact that you can use `dangerouslySetInnerHTML` if you like. That's why I don't understand the warning in the README. 😅

**Comment by tommoor** [comment]
Cleaning up the issues on this repo, closing out
