### ISSUE TITLE
How to use a Custom Images using cnd

### ISSUE THREAD

**Issue by shabtaisharon** [tommoor/react-emoji-render#32]
Hi,

I want to be able to create an apple look emojis in my app and I thought to use https://cdnjs.com/libraries/wdt-emoji-bundle which gives you an apple sheet, but I can't seem to make it work.
Can you please give me some advice on how to do that?
My general purpose is to be able to render emojis that will look like the apple emojis on all platforms.

Thanks much,
Sharon

**Comment by enzoferey** [comment]
Hi @shabtaisharon !

Have you checked the [Custom Images](https://github.com/tommoor/react-emoji-render#custom-images) section in the README ? 

You can pretty much write a HoC for any provider you choose (`wdt-emoji-bundle` if you like). You may find relevant [this line](https://github.com/tommoor/react-emoji-render/blob/master/src/renderer.js#L43) where how the final `src` attribute of the emoji is defined, so you know what options you should set in your HoC.

Let me know if you have any problems 👍

**Comment by shabtaisharon** [comment]
Hi @enzoferey,

Thanks for replying to my question.
I'm new to emojis and for some reason, I can't make this custom cdn work. Maybe I'm doing it all wrong.
I can't seem to understand what should my `baseUrl` be? maybe `wdt-emoji-bundle` is not a good candidate for the apple emojis?

**Comment by enzoferey** [comment]
Right, `wdt-emoji-bundle` is not a emojis CDN, just an emoji picker. You will need to find a CDN that serves every emoji individually under their codepoint values such as Emojione or Twemoji.
