### ISSUE TITLE
Is there a way to set margin:0?

### ISSUE THREAD

**Issue by ShimiSun** [tommoor/react-emoji-render#33]
I've tried multiple ways to remove the margins with no luck.
I need to render the emojis without the margin, otherwise, it creates layout problem for responsive.

I've tried the following: 
`<Emoji text={name} style={{ margin: 0 }} />`
and 
```
import styled from "styled-components";

const StyledAEmoji = styled(Emoji)`
  margin: 0;
`;
```
              
Can you provide an alternative way to remove margin when using one Emoji?

**Comment by tommoor** [comment]
You should use the `onlyEmojiClassName` prop, as deleted here: 
https://github.com/tommoor/react-emoji-render#only-emoji

If you're using styled components it'll be something like

```javascript
import styled from "styled-components";

const StyledAEmoji = styled(Emoji)`
  margin: 0;
`;

**Comment by ShimiSun** [comment]
Thanks, I'll give it a try and keep you updated!

**Comment by ShimiSun** [comment]
Unfortunately, it didn't work, see this sandbox that reproduces the problem: https://codesandbox.io/s/6vzr0r16oz

the className applied by `onlyEmojiClassName` is being applied on the upper DOM level rather than on the `span` that wraps the emoji.
![screen shot 2019-03-05 at 3 10 11 pm](https://user-images.githubusercontent.com/6320236/53841486-29a81a80-3f5a-11e9-9ea9-0e4760d76460.png)
Is there a workaround I can use to make it work?

**Comment by tommoor** [comment]
```
const StyledEmoji = styled(Emoji)`
  .style-emoji > span {
    margin: 0;
  }
`;
```

would be the owrkaround

**Comment by ShimiSun** [comment]
So I don't think styled-components are accepting class. and I ended up not using `onlyEmojiClassName` and just doing: 
```
const StyledEmoji = styled(Emoji)`
  span {
    margin: 0px !important;
  }
`;

...
<StyledEmoji text=":+1:" />
```
and the `!important` was a mustin order to override the inline style.

**Comment by ShimiSun** [comment]
@tommoor feel free to close this issue, I was able to work around it.

Just an FYI, in case you are interested to see the React.js+ Grommet example that uses the react-emoji-render library, take a look at 
Demo: https://l1klxkjwm.codesandbox.io/ 
Source: https://codesandbox.io/s/l1klxkjwm
