### ISSUE TITLE
:male-singer: emoji isn't showing although it exists on EmojioneV4

### ISSUE THREAD

**Issue by ShimiSun** [tommoor/react-emoji-render#34]
the :male-singer: emoji isn't showing, see here:
https://codesandbox.io/s/nw7ppjjjym

Although the emoji does exist on the `EmojioneV4` lib and should be displayed.

**Comment by enzoferey** [comment]
That's because it's not on the [aliases](https://github.com/tommoor/react-emoji-render/blob/master/data/aliases.js) list. You can submit a PR for that 👍

**Comment by tommoor** [comment]
All missing emoji are now present in `v1.0.0`
