### ISSUE TITLE
How to specify or apply emoji theme with `toArray`?

### ISSUE THREAD

**Issue by gencer** [tommoor/react-emoji-render#39]
Due to custom handling, I need to use `toArray` so that i can manipulate data before render.

In this case how can i specify emoji theme to `Emojione` for rendering? Currently when I manipulate data, emoji gets rendered on native browser emojis. When data not manipulated then emojione takes control (if-else).

**Sample**:
```typescript
markChunks(child) {
 // custom manipulation.
  return newChild
}

handleEmoji(child) {
  const emojisArray = toArray(value)
  const newValue = emojisArray.reduce((previous, current: any) => {
  if (typeof current === "string") {
   return previous + current
  }
   return previous + current.props.children
  }, "")
  return this.markChunks(newValue) // Here i manipulate data before render in markChunks function
}

render() {
  const { text } = this.props
  return (this.handleEmoji(text))
}
```

What `markChunks` does here is, mark specific words in text with yellow background so that user can see what they filtered. This text can be all string-only or may contain emojis. So i need to replace matching occurrences with `<mark>` before gets rendered.

Using 1.0.0 via TypeScript/React

Or if you know any workaround with `<Emojione ... />` i can try that too. But currently replacing text argument will result encoded html on render.

**Comment by gencer** [comment]
Well, React render does allow arrays so, changing last return from:

```
return previous + current.props.children
```

to:

```
return [previous, <Emojione svg className={styles.emoji} text={current.props.children || ""} />]
```

solved my problem.

And of course we need to replace text on `string` case.

**Comment by sinnbeck** [comment]
Is this broken now? If I try to output multiple smileys after each other, the first two are set as `[object, Object]`

Input
```
parseEmojis(':) :p :D')
```
Output 
![image](https://user-images.githubusercontent.com/13980140/107617003-5d644280-6c4f-11eb-9444-94c071cdcd30.png)
