### ISSUE TITLE
Issue with space characters

### ISSUE THREAD

**Issue by kytwb** [tommoor/react-emoji-render#4]
If I try to render the string `Ewww <3`, the emoji is right next to `Ewww`, the space is trimmed or something. For it to render properly, I need to put two space characters: `Ewww  <3`.
**Edit:** This is also the case in the live demo for the last space before the last emoji.

**Comment by kytwb** [comment]
@tommoor I'm keen to fix this bug, but later. Should be able to submit a PR later tonight (UTC+7) or tomorrow.

**Comment by tommoor** [comment]
Right on - I won't get chance to tackle in the next 24 hours so go ahead and give it a bash if you can, that would be fantastic 😄

**Comment by kytwb** [comment]
@tommoor been a bit busy, but will go a tackle this one asap.
