### ISSUE TITLE
Could not find a declaration file for module 'react-emoji-render'

### ISSUE THREAD

**Issue by SilinaGeorge** [tommoor/react-emoji-render#45]
I'm trying to import the following 
`import { Emojione } from 'react-emoji-render';`

but I am getting the following error:

> Could not find a declaration file for module 'react-emoji-render'. 'c:/pathtomodules/node_modules/react-emoji-render/lib/index.js' implicitly has an 'any' type

here are my dependencies 

 "dependencies": {
    "@material-ui/core": "^4.8.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "bootstrap": "^4.4.1",
    "query-string": "^6.9.0",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-emoji": "^0.5.0",
    "react-emoji-render": "^1.2.0",
    "react-redux": "^7.1.3",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.3.0",
    "react-scroll": "^1.7.15",
    "react-scroll-to-bottom": "^1.3.2",
    "redux": "^4.0.5",
    "socket.io-client": "^2.3.0"
  }

**Comment by tommoor** [comment]
It sounds like your typing library complaining that there is not an exported type from the module, I wouldn't consider this a bug or issue with the library. Are you sure it's an error, this type of thing would typically be a warning.
