### ISSUE TITLE
index.d.ts file isn't included in the npm package!!

### ISSUE THREAD

**Issue by AhmedMKamal** [tommoor/react-emoji-render#49]
Hi @tommoor, first off I appreciate your work 🙂 this is a very cool lib, but there's a tiny issue that I'm facing, I can tell that you included the types definitions file `index.d.ts` to the git repo but for some reason when I install your lib using npm the definitions file isn't included with the package, any ideas on why this is happening?

**Comment by enzoferey** [comment]
Hey @AhmedMKamal ! It's indeed missing https://github.com/tommoor/react-emoji-render/blob/master/package.json#L13. @tommoor I let you fix it and publish as I don't have publish rights 😄

**Comment by tommoor** [comment]
Thanks, fixed in `v1.2.2`
