### ISSUE TITLE
Non-createElement not working in demo

### ISSUE THREAD

**Issue by reintroducing** [tommoor/react-emoji-render#53]
I was just trying out the code sandbox and forked it to try using the non-createElement version. It does not seem to be working: https://codesandbox.io/s/nameless-water-20wcs?file=/src/index.js

**Comment by tommoor** [comment]
Use a template string like so:

```javascript
<Emoji text={`This ❤️ sentence \uD83C\uDF4E\uD83C\uDF4E\uD83C\uDF49\uD83C\uDF4E\uD83D\uDE0A includes :+1: a variety of emoji types :woman::skin-tone-2: normalized and rendered :)`} />,
```
