### ISSUE TITLE
emoji detection too eager?

### ISSUE THREAD

**Issue by obfusk** [tommoor/react-emoji-render#54]
`:heart:oops` becomes `❤️open_mouth:ops`
`https://foo:oops@example.com` becomes `https://foo😮ops@example.com`

See also jitsi/jitsi-meet#6501.

**Comment by enzoferey** [comment]
Thanks for reporting @obfusk 👍 

I commented at https://github.com/jitsi/jitsi-meet/issues/6501#issuecomment-623969395.

Indeed, these two cases should not happen. First one is something I have encountered in the past already I remember and I thought was fixed, but it looks like it's not. I will check it out.

**Comment by obfusk** [comment]
The first case happens because of ascii alias expansion: `:heart:oops` -> `:heart:open_mouth:ops`.

The second one because the url detection only detects `http|https` right before an emoji; matching edge cases as e.g. `((http|https)\S*)?` should skip entire urls.

**Comment by obfusk** [comment]
The first case is probably easiest to fix by changing the algorithm from
* expand ascii aliases (e.g. `:o` to `:open_mouth:`)
* replace emoji aliases (e.g. `:open_mouth:` to :open_mouth:)

to
* replace emoji aliases (e.g. `:heart:` to :heart:)
* expand ascii aliases (e.g. `:o` to `:open_mouth:`)
* replace emoji aliases again
