### ISSUE TITLE
Missing emoji

### ISSUE THREAD

**Issue by robecor** [tommoor/react-emoji-render#6]
Hello. I've been using this together with emoji-mart and it works great.
A small problem I have is that the package does not render some emojis. They are probably not included.
It would be great if you could add them in the future.
I've made a list of the emojins which are not rendered:
:slightly_smiling_face
:upside_down_face
:money_mouth_face
:nerd_face
:hugging_face
:face_with_rolling_eyes
:thinking_face
:slightly_frowning_face
:white_frowning_face
:zipper_mouth_face
:face_with_thermometer
:face_with_head_bandage
:robot_face
:middle_finger
:raised_hand_with_fingers_splayed
:the_horns
:spock-hand
:writing_hand
:eye
:speaking_head_in_silhouette
:sleuth_or_spy
:woman-heart-woman
:man-heart-man
:woman-kiss-woman
:man-kiss-man
:man-woman-girl
:man-woman-girl-boy
:man-woman-boy-boy
:man-woman-girl-girl
:woman-woman-boy
:woman-woman-girl
:woman-woman-girl-boy
:woman-woman-boy-boy
:woman-woman-girl-girl
:man-man-boy
:man-man-girl
:man-man-girl-boy
:man-man-boy-boy
:man-man-boy-boy
:man-man-girl-girl
:helmet_with_white_cross
:dark_sunglasses

I've removed the second ":" because github renders some of them as icons.

**Comment by tommoor** [comment]
Thanks for reporting! FWIW it looks like everything works correctly if the native UTF16 character is inserted, so it's just the shortnames that are missing for these characters

**Comment by kytwb** [comment]
Willing to take on this one.

**Comment by zbrukas** [comment]
Also, no flag emojis? :(

**Comment by tommoor** [comment]
Hey @zbrukas - flag Emoji's have been around for a long time, they work fine in my testing. Please submit a new issue with reproduction steps if you're having problems 😄

**Comment by tomredman** [comment]
Would love to have these added in :) Any updates? I could also take it on if it's not yet done @kytwb.

Thanks for the package @tommoor, super clean!

**Comment by kytwb** [comment]
Feel free @tomredman! 💯

**Comment by logicminds** [comment]
What is needed to add these?

**Comment by tommoor** [comment]
It's as simple as adding the aliases to the data file, the same as this PR did:

https://github.com/tommoor/react-emoji-render/pull/10

**Comment by tommoor** [comment]
All missing emoji are now present in `v1.0.0`
