### ISSUE TITLE
Show all emojis

### ISSUE THREAD

**Issue by aFrontendDev** [tommoor/react-emoji-render#63]
Hi, I'm putting something together that would allow a user to select an emoji (like you can in slack) so am iterating over the aliases (copied from the data folder) but I'm getting some not rendering  like "flag-zw": "🇿🇼" & zw: "🇿🇼"

These do render if I used the twitter emoji option that you have though. 

Is there any way to know if an emoji is supported by the standard emoji set at all?

Thanks and really love what's been built here, great work

**Comment by tommoor** [comment]
> Is there any way to know if an emoji is supported by the standard emoji set at all?

Not really, it depends on the OS and typeface to know if an emoji will display, this is why so many sites just use img tags instead.

**Comment by aFrontendDev** [comment]
Fair enough, thanks for the quick response 👍
