### ISSUE TITLE
Missing Twemojis

### ISSUE THREAD

**Issue by samajammin** [tommoor/react-emoji-render#68]
Hey folks - first off, thanks for creating this great package!

I've been using this for the Twemoji support & in general it works great but I just noticed there's some missing Twemojis, e.g. `:bricks:`.

Brick has seemingly been in Twemoji since 11.0 (released on June 5, 2018)
https://emojipedia.org/twitter/twemoji-11.0/brick/

Perhaps we need to update the CDN referenced?
https://github.com/tommoor/react-emoji-render/blob/master/src/index.js#L20
I believe updating it to use latest would fix this. i.e. updating
```
baseUrl: `//twemoji.maxcdn.com/2/${svg ? "svg/" : ""}`,
```
to
```
baseUrl: `//twemoji.maxcdn.com/v/latest/${svg ? "svg/" : ""}`,
```

**Comment by samajammin** [comment]
Hmmm... tried updating the `baseUrl` without any luck.

It appears `:bricks:` is accessible via the current baseUrl:
https://twemoji.maxcdn.com/2/svg/1f9f1.svg

But something about how this package parses the string `:bricks:` into the unicode `1f9f1` appears to be broken...

Any insight greatly appreciated!

**Comment by enzoferey** [comment]
Hey @samajammin ! Sorry for the late answer, did you find any fixes to the issue ?

I just tried:

```tsx
<Twemoji text=":brick:" />
<Twemoji svg={true} text=":brick:" />
```

And both are outputting the correct emoji => https://codesandbox.io/s/brick-trial-vcgd5

**Comment by enzoferey** [comment]
I'm closing because this issue has become stale. @samajammin please feel free to comment if this is still an issue and I will be glad to reopen 👍🏻
