### ISSUE TITLE
Expected a component class, got [object Object]

### ISSUE THREAD

**Issue by kytwb** [tommoor/react-emoji-render#7]
Only in React Native.

![desctop screenshot](https://cloud.githubusercontent.com/assets/412895/26233197/e023a704-3c85-11e7-8739-99b9cfce06b6.png)

**Comment by kytwb** [comment]
I've been wrapping the output in a `Text` element I pass through `props.component`.
I'm now struggling on this error: `undefined is not a function (evaluating 'input[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')`. Might have to do with babel and presets.

**Comment by tommoor** [comment]
Did you find a solution? I haven't tested this with react native at all

**Comment by kytwb** [comment]
@tommoor I'm working on a solution on my fork right now but not working yet. Will update as soon as I get back on it!
