### ISSUE TITLE
Typescript support: index.d.ts is not exporting EmojioneV4

### ISSUE THREAD

**Issue by gabrielgatu** [tommoor/react-emoji-render#70]
When using this library in TS I have to import directly from the lib/index file because the index.d.ts file has not been updated with EmojioneV4.

I should be able to do:
`import { EmojioneV4 } from "react-emoji-render"`

instead of:
`import { EmojioneV4 } from "react-emoji-render/lib"`

Thanks for the library! 🙂

**Comment by enzoferey** [comment]
Hi @gabrielgatu ! You are right, we should add a `EmojioneV4` declaration with the `size` property instead of `svg` property. Would you be able to do a PR ?

**Comment by gabrielgatu** [comment]
Hey, sorry for the delay... I'm pretty overwhelmed right now with work at my startup :(
Maybe I could send a PR by the end of this month if no one else does it, I'm gonna keep my eye on this issue.

Cheers!
