### ISSUE TITLE
Render using react children

### ISSUE THREAD

**Issue by clementdevos** [tommoor/react-emoji-render#73]
Hi, 

I'm having trouble coupling [linkify-react](https://soapbox.github.io/linkifyjs/docs/linkify-react.html) with react-emoji-render. 

The issue here is that Linkify loops all of its children recursively to find text and replace the urls with <a> tags and skips the element if it has no children (https://github.com/Soapbox/linkifyjs/blob/master/src/linkify-react.js#L65)

Unfortunately, react-emoji-render doesn't use children but a text props. 

Is there a reason (performance?) react-emoji-render doesn't proceed the same way with children? 
Looping all children would enable to work with more complex paragraphs etc etc...

Cheers !

**Comment by tommoor** [comment]
It looks like an interesting approach, I'd probably accept a PR to add support for this kind of operation! I think the limitation is that folks expect to be able to render text from child components and have it work, but of course it will only work with plaintext strings.

**Comment by clementdevos** [comment]
I'll try to submit a PR !

**Comment by Elbarae1921** [comment]
This thread hasn't been active for a while so I took the liberty to submit a PR ( #92 ) that fixes this issue.

**Comment by enzoferey** [comment]
Closed via https://github.com/tommoor/react-emoji-render/pull/92. Thanks @Elbarae1921 🎉

**Comment by clementdevos** [comment]
Sorry I couldn't provide any PR for this 🫢

Thanks @Elbarae1921 !
