### ISSUE TITLE
Twemojis for skateboard and Nazar amulet appear missing

### ISSUE THREAD

**Issue by dooski** [tommoor/react-emoji-render#74]
I've tried to render the Twemoji for skateboard and Nazar amulet using the following code:

```jsx
<Twemoji text=":skateboard:"/>
<Twemoji text=":nazar_amulet:"/>
```

They return 🛹 and 🧿 respectively, but not the Twemoji versions which have both been included in Twemoji since 11.0. I've also tried the unicode format with the same results. I'm using about 19 other Twemojis, all of which render correctly.

(Never submitted an issue before on GitHub so hope I included everything necessary!)

**Comment by enzoferey** [comment]
Related to https://github.com/tommoor/react-emoji-render/issues/68.
