### ISSUE TITLE
Problems in documentation

### ISSUE THREAD

**Issue by sinnbeck** [tommoor/react-emoji-render#75]
It seems that the docs are a bit off?

For instance it says to use `size={32}` to change the size of the EmojioneV4 component. But I believe that it should be sent in using `options={}`

```
<EmojioneV4 options={{size: 32}} text=":)" />
```
It would also be nice if the documentation mentioned that you can pass in `className` in that same options object

**Comment by enzoferey** [comment]
Hi @sinnbeck !

Looking at the component [signature](https://github.com/tommoor/react-emoji-render/blob/master/src/index.js#L56), it shouldn't be the case. `size` as a property should work.

I just tried it at https://codesandbox.io/s/heuristic-tharp-l8e7t?file=/src/index.js and it works as expected, you can change the `size` property and you will see how the image looks blurry as it won't be big enough and we are forcing its size with `fontSize`.

Passing `className` and other attributes are all supported yes. Please feel free to open a PR to improve docs 👍🏻
