### ISSUE TITLE
Making bigger emojis

### ISSUE THREAD

**Issue by cosydney** [tommoor/react-emoji-render#77]
Hey, 

Thank you for your package. 

Can't seem to find through the documentation but is this suppose to make the emoji bigger: 

```javascript
<Emoji size={128} text={"🐣"} />
```

Thank you, 

Regards

**Comment by enzoferey** [comment]
Hi @cosydney !

Indeed the docs could do a better job at explaining this property. The `size` property is only supported when you use the `EmojioneV4` component and it may be 32, 64 (default), or 128 as specified [here](https://github.com/tommoor/react-emoji-render#emojione).

What are you trying to do ?

**Comment by acoudouy** [comment]
Following on Sydney's message, I'm trying to make big emojis using Twemoji
` <Twemoji text="😎" onlyEmojiClassName="make-emojis-large" />`
` <Twemoji options={{ size: "100x100" }} text="😎" />`

I tried these two solutions but can't make it work, can you help me out please ?

**Comment by cosydney** [comment]
Thanks for answering so fast @enzoferey . Ideally would like to make this one bigger: 

```javascript
<Emoji size={128} text={"🐣"} />
```

I guess I will look at the CSS and try to add a class to it, unless you have something else to recommend? 

Cheers, 

Sydney

**Comment by enzoferey** [comment]
@acoudouy and @cosydney you should be able to set a `font-size` in the context where this emoji is being used and it should work. You can see from the styles that we use `1em` for width and height of the emoji.

You can check [this CodeSanbox](https://codesandbox.io/s/heuristic-tharp-l8e7t?file=/src/index.js) where at the bottom of the page I'm setting a `div` that defines `font-size: 128px` and you can see how all emoji inside it readjust accordingly.

@acoudouy in the case where you want to use `onlyEmojiClassName`, you can provide a class that sets the `font-size` to whatever value you which.

**Comment by cosydney** [comment]
Thank you @enzoferey this is exactly what we were looking for !
