### ISSUE TITLE
Flag emojis missing

### ISSUE THREAD

**Issue by zbrukas** [tommoor/react-emoji-render#9]
I've tried to use the library to output flag emojis. Code is pretty straightforward:

```js
<p>
      <Emoji text=":flag-pt:" />
      <Emoji text=":flag-de:" />
      <Emoji text=":flag-dk:" />
      <Emoji text=":flag-us:" />
      <Emoji text=":flag-PT:" />
      <Emoji text=":flag-br:" />
</p>
```

Output is:
```:flag-pt::flag-de::flag-dk::flag-us::flag-PT::flag-br:```
as regular text

Emojipedia had those codes as the ones for flags, last time I checked.

**Comment by tommoor** [comment]
Interesting, the flags are available but without the "flag-" prefix, for example: https://github.com/tommoor/react-emoji-render/blob/master/data/aliases.js#L662

**Comment by zbrukas** [comment]
Nice, I looked into the aliases but I missed those ones :( is there a plan to add the remaining flags?

**Comment by tommoor** [comment]
If I can find an existing list then happy to add the aliases, otherwise it'll be a manual affair! Lets keep this issue open until they are added

**Comment by leimd** [comment]
We have forked this project and added a few aliases for Currencies, would you be interested to get this fork merged into the main branch? https://github.com/beanworks/react-emoji-render/blob/master/data/currencyAliases.js we can also take on this job for adding flags if the currencies can be merged.

**Comment by Foorack** [comment]
A pull request has now been made to fix this https://github.com/tommoor/react-emoji-render/pull/31
